pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDAutoLayout', '~> 1.3'
pod 'Masonry'
pod 'SDCycleScrollView','~> 1.64'